Repository woowa-techcamp-2021/cashbook-16, pull requests merged in 2021-08, with the labels that each got.

#40 Feat apis
  server/src/app.ts
  server/src/controllers/CategoryController.ts
  server/src/controllers/HistoryController.ts
  server/src/controllers/MethodController.ts
  server/src/controllers/UserController.ts
  server/src/entity/paymentHistory.entity.ts
  server/src/entity/paymentMethod.entity.ts
  server/src/index.ts
  server/src/routes/category.ts
  server/src/routes/history.ts
  server/src/routes/method.ts
  server/src/routes/router.ts
  server/src/routes/user.ts
  server/src/services/CategoryService.ts
  server/src/services/HistoryService.ts
  server/src/services/MethodService.ts
Labels: BE

#46 Feat middlewares
  client/src/view/pages/login.ts
  server/.env.defaults
  server/src/app.ts
  server/src/errors/ErrorController.ts
  server/src/errors/customErrors.ts
  server/src/middlewares/auth.ts
  server/src/routes/router.ts
  server/src/services/CategoryService.spec.ts
  server/src/services/MethodService.spec.ts
Labels: BE

#47 setup: client tailwind.css 설정
  client/package.json
  client/postcss.config.js
  client/src/index.ts
  client/src/view/pages/list.ts
  client/tailwind.config.js
  client/webpack.common.js
  client/yarn.lock
Labels: FE

#48 client css setup
  client/assets/logo.png
  client/src/assets.d.ts
  client/src/index.ts
  client/src/view/pages/list.ts
  client/src/view/pages/logo.png
  client/src/view/styles/index.css
  client/src/view/styles/reset.css
  client/tailwind.config.js
  client/tsconfig.json
  client/webpack.common.js
Labels: FE

#52 Feat list page 관련 컴포넌트 작성
  client/src/index.ts
  client/src/view/customElements/app-header.ts
  client/src/view/customElements/list-item.ts
  client/src/view/customElements/list-title.ts
  client/src/view/pages/list.ts
  server/src/app.ts
Labels: FE

#56 feat: router default page 기능 추가
  client/src/core/router.ts
  client/src/index.ts
Labels: FE

#60 Feat list create 및 입금 출금 필터링
  client/src/api/apis.ts
  client/src/controller/controller.ts
  client/src/controller/history.ts
  client/src/store/history.ts
  client/src/utils.ts
  client/src/view/customElements/category-select.ts
  client/src/view/customElements/history-form.ts
  client/src/view/customElements/history-list.ts
  client/src/view/customElements/index.ts
  client/src/view/customElements/method-select.ts
  client/src/view/customElements/pay-type.ts
  client/src/view/pages/list.ts
  client/src/view/pages/login.ts
  server/src/controllers/HistoryController.ts
  server/src/services/HistoryService.ts
Labels: BE, FE

#61 fix: method githubid 제거
  client/src/types/index.ts
  server/src/controllers/MethodController.ts
  server/src/entity/paymentMethod.entity.ts
  server/src/services/CategoryService.ts
  server/src/services/MethodService.ts
Labels: BE, FE

#63 feat: applychanges 추가
  server/src/controllers/HistoryController.ts
  server/src/routes/history.ts
  server/src/services/HistoryService.ts
Labels: BE

#64 feat: 메소드 수정 및 apply 파라미터 methodName으로 변경
  server/src/DTO/HistoryApplyDto.ts
  server/src/controllers/HistoryController.ts
  server/src/controllers/MethodController.ts
  server/src/entity/paymentHistory.entity.ts
  server/src/routes/router.ts
  server/src/services/MethodService.spec.ts
  server/src/services/MethodService.ts
Labels: BE

#65 Feat backend apply change 수정
  client/src/DTO/category.ts
  client/src/DTO/history.ts
  client/src/DTO/method.ts
  client/src/api/apis.ts
  client/src/api/histories.ts
  client/src/controller/calendar.ts
  client/src/controller/history.ts
  client/src/store/store.ts
  client/src/store/time.ts
  client/src/utils.ts
  client/src/view/components/Calendar.ts
  client/src/view/components/CalendarModal.ts
  client/src/view/components/EditableRow.ts
  client/src/view/components/UserInfo.ts
  client/src/view/components/component.ts
  client/src/view/pages/calendar.ts
  client/src/view/pages/list.ts
  client/src/view/pages/login.ts
  client/src/view/pages/page.ts
  server/src/DTO/HistoryApplyDto.ts
  server/src/controllers/HistoryController.ts
  server/src/controllers/UserController.ts
  server/src/services/HistoryService.ts
Labels: BE

#66 feat: default day, month 수정
  client/src/view/customElements/history-form.ts
  client/src/view/pages/list.ts
Labels: FE

#67 Feat calendar page2
  client/src/api/apis.ts
  client/src/index.ts
  client/src/utils.ts
  client/src/view/components/Calendar.ts
  client/src/view/components/CalendarModal.ts
  client/src/view/components/Component.ts
  client/src/view/components/EditableRow.ts
  client/src/view/components/UserInfo.ts
  client/src/view/customElements/history-form.ts
  client/src/view/pages/calendar.ts
  client/src/view/pages/login.ts
  client/src/view/pages/main.ts
  client/src/view/styles/calendar.tailwind.css
  client/src/view/styles/income.tailwind.css
  pages/markups/calendar.html
  pages/markups/income.html
  pages/styles/calendar.tailwind.css
  pages/styles/income.tailwind.css
  server/src/middlewares/auth.ts
  server/src/routes/history.ts
  server/src/services/HistoryService.ts
Labels: FE
